// Sound groups organised by UK phonics phases
const soundGroups = [
  {
    name: "Phase 2 — Single letters",
    sounds: ["s","a","t","p","i","n","m","d","g","o","c","k","ck","e","u","r","h","b","f","l"]
  },
  {
    name: "Phase 3 — Digraphs & trigraphs",
    sounds: ["sh","ch","th","ng","ai","ee","oo","oa","ar","or","ur","ow","oi","er"]
  },
  {
    name: "Phase 4 — Consonant clusters",
    sounds: ["bl","br","cl","cr","dr","fl","fr","gl","gr","pl","pr","sc","sk","sl","sm","sn","sp","st","sw","tr"]
  },
  {
    name: "Phase 5 — Split digraphs & alternatives",
    sounds: ["a_e","i_e","o_e","u_e","ea","ie","ou","ey","ph","wh"]
  }
];

// Every word tagged with ALL its component sounds
// image: filename in images/ folder
const allWords = [
  // --- Phase 2 words (single-letter sounds only) ---
  { word: "tap", sounds: ["t","a","p"], image: "tap.png" },
  { word: "pan", sounds: ["p","a","n"], image: "pan.png" },
  { word: "pin", sounds: ["p","i","n"], image: "pin.png" },
  { word: "tin", sounds: ["t","i","n"], image: "tin.png" },
  { word: "man", sounds: ["m","a","n"], image: "man.png" },
  { word: "map", sounds: ["m","a","p"], image: "map.png" },
  { word: "dig", sounds: ["d","i","g"], image: "dig.png" },
  { word: "dog", sounds: ["d","o","g"], image: "dog.png" },
  { word: "cat", sounds: ["c","a","t"], image: "cat.png" },
  { word: "cap", sounds: ["c","a","p"], image: "cap.png" },
  { word: "kid", sounds: ["k","i","d"], image: "kid.png" },
  { word: "kick", sounds: ["k","i","ck"], image: "kick.png" },
  { word: "duck", sounds: ["d","u","ck"], image: "duck.png" },
  { word: "sock", sounds: ["s","o","ck"], image: "sock.png" },
  { word: "neck", sounds: ["n","e","ck"], image: "neck.png" },
  { word: "pet", sounds: ["p","e","t"], image: "pet.png" },
  { word: "pen", sounds: ["p","e","n"], image: "pen.png" },
  { word: "red", sounds: ["r","e","d"], image: "red.png" },
  { word: "run", sounds: ["r","u","n"], image: "run.png" },
  { word: "rug", sounds: ["r","u","g"], image: "rug.png" },
  { word: "cup", sounds: ["c","u","p"], image: "cup.png" },
  { word: "cut", sounds: ["c","u","t"], image: "cut.png" },
  { word: "sun", sounds: ["s","u","n"], image: "sun.png" },
  { word: "mug", sounds: ["m","u","g"], image: "mug.png" },
  { word: "bug", sounds: ["b","u","g"], image: "bug.png" },
  { word: "bus", sounds: ["b","u","s"], image: "bus.png" },
  { word: "bat", sounds: ["b","a","t"], image: "bat.png" },
  { word: "bed", sounds: ["b","e","d"], image: "bed.png" },
  { word: "bin", sounds: ["b","i","n"], image: "bin.png" },
  { word: "big", sounds: ["b","i","g"], image: "big.png" },
  { word: "hug", sounds: ["h","u","g"], image: "hug.png" },
  { word: "hat", sounds: ["h","a","t"], image: "hat.png" },
  { word: "hen", sounds: ["h","e","n"], image: "hen.png" },
  { word: "hit", sounds: ["h","i","t"], image: "hit.png" },
  { word: "hot", sounds: ["h","o","t"], image: "hot.png" },
  { word: "hop", sounds: ["h","o","p"], image: "hop.png" },
  { word: "fun", sounds: ["f","u","n"], image: "fun.png" },
  { word: "fan", sounds: ["f","a","n"], image: "fan.png" },
  { word: "fig", sounds: ["f","i","g"], image: "fig.png" },
  { word: "fog", sounds: ["f","o","g"], image: "fog.png" },
  { word: "leg", sounds: ["l","e","g"], image: "leg.png" },
  { word: "lid", sounds: ["l","i","d"], image: "lid.png" },

  // --- Phase 3 words (need digraphs/trigraphs) ---
  { word: "ship", sounds: ["sh","i","p"], image: "ship.png" },
  { word: "shut", sounds: ["sh","u","t"], image: "shut.png" },
  { word: "shell", sounds: ["sh","e","l","l"], image: "shell.png" },
  { word: "fish", sounds: ["f","i","sh"], image: "fish.png" },
  { word: "chop", sounds: ["ch","o","p"], image: "chop.png" },
  { word: "chat", sounds: ["ch","a","t"], image: "chat.png" },
  { word: "moth", sounds: ["m","o","th"], image: "moth.png" },
  { word: "king", sounds: ["k","i","ng"], image: "king.png" },
  { word: "ring", sounds: ["r","i","ng"], image: "ring.png" },
  { word: "sing", sounds: ["s","i","ng"], image: "sing.png" },
  { word: "song", sounds: ["s","o","ng"], image: "song.png" },
  { word: "rain", sounds: ["r","ai","n"], image: "rain.png" },
  { word: "tail", sounds: ["t","ai","l"], image: "tail.png" },
  { word: "mail", sounds: ["m","ai","l"], image: "mail.png" },
  { word: "nail", sounds: ["n","ai","l"], image: "nail.png" },
  { word: "snail", sounds: ["sn","ai","l"], image: "snail.png" },
  { word: "bee", sounds: ["b","ee"], image: "bee.png" },
  { word: "tree", sounds: ["tr","ee"], image: "tree.png" },
  { word: "seed", sounds: ["s","ee","d"], image: "seed.png" },
  { word: "feet", sounds: ["f","ee","t"], image: "feet.png" },
  { word: "moon", sounds: ["m","oo","n"], image: "moon.png" },
  { word: "boot", sounds: ["b","oo","t"], image: "boot.png" },
  { word: "food", sounds: ["f","oo","d"], image: "food.png" },
  { word: "pool", sounds: ["p","oo","l"], image: "pool.png" },
  { word: "boat", sounds: ["b","oa","t"], image: "boat.png" },
  { word: "coat", sounds: ["c","oa","t"], image: "coat.png" },
  { word: "goat", sounds: ["g","oa","t"], image: "goat.png" },
  { word: "road", sounds: ["r","oa","d"], image: "road.png" },
  { word: "car", sounds: ["c","ar"], image: "car.png" },
  { word: "star", sounds: ["st","ar"], image: "star.png" },
  { word: "park", sounds: ["p","ar","k"], image: "park.png" },
  { word: "dark", sounds: ["d","ar","k"], image: "dark.png" },
  { word: "fork", sounds: ["f","or","k"], image: "fork.png" },
  { word: "corn", sounds: ["c","or","n"], image: "corn.png" },
  { word: "horn", sounds: ["h","or","n"], image: "horn.png" },
  { word: "curl", sounds: ["c","ur","l"], image: "curl.png" },
  { word: "burn", sounds: ["b","ur","n"], image: "burn.png" },
  { word: "hurt", sounds: ["h","ur","t"], image: "hurt.png" },
  { word: "fur", sounds: ["f","ur"], image: "fur.png" },
  { word: "cow", sounds: ["c","ow"], image: "cow.png" },
  { word: "owl", sounds: ["ow","l"], image: "owl.png" },
  { word: "town", sounds: ["t","ow","n"], image: "town.png" },
  { word: "coin", sounds: ["c","oi","n"], image: "coin.png" },
  { word: "oil", sounds: ["oi","l"], image: "oil.png" },
  { word: "soil", sounds: ["s","oi","l"], image: "soil.png" },
  { word: "fern", sounds: ["f","er","n"], image: "fern.png" },

  // --- Phase 4 words (consonant clusters) ---
  { word: "flag", sounds: ["fl","a","g"], image: "flag.png" },
  { word: "frog", sounds: ["fr","o","g"], image: "frog.png" },
  { word: "drum", sounds: ["dr","u","m"], image: "drum.png" },
  { word: "drop", sounds: ["dr","o","p"], image: "drop.png" },
  { word: "crab", sounds: ["cr","a","b"], image: "crab.png" },
  { word: "clip", sounds: ["cl","i","p"], image: "clip.png" },
  { word: "clap", sounds: ["cl","a","p"], image: "clap.png" },
  { word: "plug", sounds: ["pl","u","g"], image: "plug.png" },
  { word: "plum", sounds: ["pl","u","m"], image: "plum.png" },
  { word: "grip", sounds: ["gr","i","p"], image: "grip.png" },
  { word: "brick", sounds: ["br","i","ck"], image: "brick.png" },
  { word: "black", sounds: ["bl","a","ck"], image: "black.png" },
  { word: "skip", sounds: ["sk","i","p"], image: "skip.png" },
  { word: "skin", sounds: ["sk","i","n"], image: "skin.png" },
  { word: "slim", sounds: ["sl","i","m"], image: "slim.png" },
  { word: "slug", sounds: ["sl","u","g"], image: "slug.png" },
  { word: "slip", sounds: ["sl","i","p"], image: "slip.png" },
  { word: "spot", sounds: ["sp","o","t"], image: "spot.png" },
  { word: "spin", sounds: ["sp","i","n"], image: "spin.png" },
  { word: "stem", sounds: ["st","e","m"], image: "stem.png" },
  { word: "stop", sounds: ["st","o","p"], image: "stop.png" },
  { word: "step", sounds: ["st","e","p"], image: "step.png" },
  { word: "swim", sounds: ["sw","i","m"], image: "swim.png" },
  { word: "swan", sounds: ["sw","a","n"], image: "swan.png" },
  { word: "trip", sounds: ["tr","i","p"], image: "trip.png" },
  { word: "trap", sounds: ["tr","a","p"], image: "trap.png" },
  { word: "tram", sounds: ["tr","a","m"], image: "tram.png" },
  { word: "truck", sounds: ["tr","u","ck"], image: "truck.png" },
  { word: "press", sounds: ["pr","e","s","s"], image: "press.png" },
  { word: "glad", sounds: ["gl","a","d"], image: "glad.png" },
  { word: "glass", sounds: ["gl","a","s","s"], image: "glass.png" },
  { word: "smell", sounds: ["sm","e","l","l"], image: "smell.png" },

  // --- Phase 5 words (split digraphs & alternatives) ---
  { word: "cake", sounds: ["c","a_e","k"], image: "cake.png" },
  { word: "lake", sounds: ["l","a_e","k"], image: "lake.png" },
  { word: "gate", sounds: ["g","a_e","t"], image: "gate.png" },
  { word: "game", sounds: ["g","a_e","m"], image: "game.png" },
  { word: "bike", sounds: ["b","i_e","k"], image: "bike.png" },
  { word: "kite", sounds: ["k","i_e","t"], image: "kite.png" },
  { word: "lime", sounds: ["l","i_e","m"], image: "lime.png" },
  { word: "nine", sounds: ["n","i_e","n"], image: "nine.png" },
  { word: "bone", sounds: ["b","o_e","n"], image: "bone.png" },
  { word: "home", sounds: ["h","o_e","m"], image: "home.png" },
  { word: "nose", sounds: ["n","o_e","s"], image: "nose.png" },
  { word: "rope", sounds: ["r","o_e","p"], image: "rope.png" },
  { word: "cube", sounds: ["c","u_e","b"], image: "cube.png" },
  { word: "tube", sounds: ["t","u_e","b"], image: "tube.png" },
  { word: "leaf", sounds: ["l","ea","f"], image: "leaf.png" },
  { word: "meat", sounds: ["m","ea","t"], image: "meat.png" },
  { word: "bean", sounds: ["b","ea","n"], image: "bean.png" },
  { word: "seal", sounds: ["s","ea","l"], image: "seal.png" },
  { word: "peach", sounds: ["p","ea","ch"], image: "peach.png" },
  { word: "pie", sounds: ["p","ie"], image: "pie.png" },
  { word: "tie", sounds: ["t","ie"], image: "tie.png" },
  { word: "cloud", sounds: ["cl","ou","d"], image: "cloud.png" },
  { word: "mouse", sounds: ["m","ou","s"], image: "mouse.png" },
  { word: "house", sounds: ["h","ou","s"], image: "house.png" },
  { word: "phone", sounds: ["ph","o_e","n"], image: "phone.png" },
  { word: "whale", sounds: ["wh","a_e","l"], image: "whale.png" },
  { word: "wheel", sounds: ["wh","ee","l"], image: "wheel.png" },
  { word: "white", sounds: ["wh","i_e","t"], image: "white.png" },
  { word: "key", sounds: ["k","ey"], image: "key.png" },
  { word: "monkey", sounds: ["m","o","n","k","ey"], image: "monkey.png" },
  { word: "honey", sounds: ["h","o","n","ey"], image: "honey.png" },
];
